---
name: terraform-prepare

permissions: read-all

on:
  pull_request:
    branches:
      - "master"

jobs:
  tf-fmt:
    runs-on: ubuntu-latest
    name: Check terraform file format
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Terraform fmt
        uses: dflook/terraform-fmt-check@19eefb5181b0a7de8f8198aef270454f4671d15a # v1
        with:
          path: /
